# Generated by Django 3.2.18 on 2023-03-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
