# Generated by Django 3.2.7 on 2023-04-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_like_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='movies.Hashtag'),
        ),
    ]
