# Generated by Django 3.2.13 on 2023-04-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230414_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='movie_like_users',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie_like_users',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_followings',
            old_name='user_id',
            new_name='user',
        ),
    ]
