# Generated by Django 3.2.13 on 2023-04-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230414_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_followings',
        ),
    ]
