# Generated by Django 3.2.7 on 2023-04-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='articles.Article'),
        ),
    ]
