# Generated by Django 3.2.7 on 2023-04-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_hashtag_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='article',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='articles.Hashtag'),
        ),
    ]
